openapi: 3.0.0
info:
  title: 沙箱 API
  description: 用于安全运行 Python 代码的沙箱 API
  version: 1.0.0

paths:
  /workspace/se/session/{session_id}:
    post:
      summary: 创建新的会话
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            description: 会话 ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                size:
                  type: string
                  default: "50M"
                  description: tmpfs 挂载点大小
      responses:
        '200':
          description: 会话创建成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      session_id:
                        type: string
                        description: 创建的会话 ID
    delete:
      summary: 删除会话
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            description: 会话 ID
      responses:
        '200':
          description: 会话删除成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      status:
                        type: string
                        enum: [success]

  /workspace/se/upload/{session_id}:
    post:
      summary: 上传文件到会话
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            description: 会话 ID
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: 要上传的文件
                filename:
                  type: string
                  description: 可选的文件名，如果不提供则使用原始文件名
      responses:
        '200':
          description: 文件上传成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      filename:
                        type: string
                        description: 保存的文件名
                      size:
                        type: integer
                        description: 文件大小（字节）

  /workspace/se/download/{session_id}/{filename}:
    get:
      summary: 从会话下载文件
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            description: 会话 ID
        - name: filename
          in: path
          required: true
          schema:
            type: string
            description: 要下载的文件名
      responses:
        '200':
          description: 文件下载成功
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary

  /workspace/se/create/{session_id}:
    post:
      summary: 创建脚本文件
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            description: 会话 ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                  description: 脚本内容
                script_type:
                  type: string
                  enum: [python, shell]
                  default: python
                  description: 脚本类型
                filename:
                  type: string
                  description: 可选的文件名，如果不提供则自动生成
      responses:
        '200':
          description: 脚本创建成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      filename:
                        type: string
                        description: 创建的文件名
                      type:
                        type: string
                        description: 脚本类型

  /workspace/se/execute/{session_id}:
    post:
      summary: 执行脚本文件
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            description: 会话 ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                filename:
                  type: string
                  description: 要执行的文件名
                args:
                  type: array
                  items:
                    type: string
                  description: 命令行参数列表
                input_files:
                  type: array
                  items:
                    type: string
                  description: 输入文件列表
                output_files:
                  type: array
                  items:
                    type: string
                  description: 输出文件列表
      responses:
        '200':
          description: 脚本执行成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      stdout:
                        type: string
                        description: 标准输出
                      stderr:
                        type: string
                        description: 标准错误
                      returncode:
                        type: integer
                        description: 返回码

  /workspace/se/execute_code/{session_id}:
    post:
      summary: 直接执行代码
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            description: 会话 ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                  description: 要执行的代码
                filename:
                  type: string
                  description: 可选的文件名，如果不提供则自动生成
                args:
                  type: array
                  items:
                    type: string
                  description: 命令行参数列表
                script_type:
                  type: string
                  enum: [python, shell]
                  default: python
                  description: 脚本类型
      responses:
        '200':
          description: 代码执行成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      stdout:
                        type: string
                        description: 标准输出
                      stderr:
                        type: string
                        description: 标准错误
                      returncode:
                        type: integer
                        description: 返回码

  /workspace/se/files/{session_id}:
    get:
      summary: 列出会话中的所有文件
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            description: 会话 ID
      responses:
        '200':
          description: 文件列表获取成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      files:
                        type: array
                        items:
                          type: object
                          properties:
                            filename:
                              type: string
                              description: 文件名
                            size:
                              type: integer
                              description: 文件大小（字节）
                            type:
                              type: string
                              description: 文件类型

  /workspace/se/workspaces:
    get:
      summary: 列出所有工作区
      responses:
        '200':
          description: 工作区列表获取成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      workspaces:
                        type: object
                        description: 工作区信息映射

  /workspace/se/readfile/{session_id}/{filename}:
    get:
      summary: 分次读取文件内容
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            description: 会话 ID
        - name: filename
          in: path
          required: true
          schema:
            type: string
            description: 文件名
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
            description: 读取起始位置（字节）
        - name: buffer_size
          in: query
          schema:
            type: integer
            default: 4096
            description: 读取缓冲区大小（字节）
      responses:
        '200':
          description: 文件内容读取成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      content:
                        type: string
                        description: 文件内容（base64编码的二进制数据）
                      is_binary:
                        type: boolean
                        description: 是否为二进制数据
                      offset:
                        type: integer
                        description: 下一个读取位置
                      size:
                        type: integer
                        description: 文件总大小
                      is_eof:
                        type: boolean
                        description: 是否到达文件末尾

  /workspace/se/doc:
    get:
      summary: 获取 API 文档
      responses:
        '200':
          description: API 文档获取成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    description: API 文档内容

  /workspace/se/cleanup-all:
    post:
      summary: 清理所有虚拟环境
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                force:
                  type: boolean
                  default: false
                  description: 是否强制清理
      responses:
        '200':
          description: 环境清理成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      total:
                        type: integer
                        description: 总环境数
                      success:
                        type: integer
                        description: 成功清理数
                      failed:
                        type: array
                        items:
                          type: string
                        description: 清理失败的环境列表
                      skipped:
                        type: array
                        items:
                          type: string
                        description: 跳过的环境列表

  /workspace/se/status/{session_id}:
    get:
      summary: 获取会话状态
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            description: 会话 ID
      responses:
        '200':
          description: 会话状态获取成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      id:
                        type: string
                        description: 会话 ID
                      exists:
                        type: boolean
                        description: 会话是否存在
                      created_at:
                        type: number
                        format: float
                        description: 创建时间戳
                      mount_point:
                        type: string
                        description: 挂载点路径
                      is_mounted:
                        type: boolean
                        description: 是否已挂载
                      files:
                        type: array
                        items:
                          type: object
                          properties:
                            filename:
                              type: string
                              description: 文件名
                            size:
                              type: integer
                              description: 文件大小
                            type:
                              type: string
                              description: 文件类型
                            modified_at:
                              type: number
                              format: float
                              description: 最后修改时间

components:
  schemas:
    Error:
      type: object
      properties:
        detail:
          type: string
      required:
        - detail

tags:
  - name: Session
    description: 会话管理相关接口
  - name: File
    description: 文件操作相关接口
  - name: Script
    description: 脚本执行相关接口
  - name: Workspace
    description: 工作区管理相关接口 