openapi: 3.0.0
info:
  title: SSH Sandbox API
  description: |
    SSH 沙箱环境管理 API，提供基于 SSH 的虚拟环境创建、管理和清理功能。
    支持文件上传、下载、命令执行等操作。
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: http://localhost:8000
    description: 本地开发服务器
  - url: https://api.example.com
    description: 生产环境服务器

paths:
  /workspace/ssh/session/{session_id}:
    post:
      summary: 创建新的会话
      description: 创建一个新的 SSH 沙箱会话环境
      operationId: createSession
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
          description: 会话ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                size:
                  type: string
                  default: "50M"
                  description: tmpfs 大小
      responses:
        '200':
          description: 会话创建成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      session_id:
                        type: string
        '400':
          description: 会话ID已存在
        '500':
          description: 服务器内部错误

    delete:
      summary: 删除会话
      description: 删除指定的 SSH 沙箱会话环境
      operationId: deleteSession
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
          description: 会话ID
      responses:
        '200':
          description: 会话删除成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      status:
                        type: string
                        enum: [success]
        '404':
          description: 会话不存在
        '500':
          description: 服务器内部错误

  /workspace/ssh/upload/{session_id}:
    post:
      summary: 上传文件
      description: 上传文件到指定的 SSH 会话环境
      operationId: uploadFile
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
          description: 会话ID
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                remote_path:
                  type: string
                  description: 远程文件路径（可选）
      responses:
        '200':
          description: 文件上传成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      filename:
                        type: string
                      size:
                        type: integer
        '404':
          description: 会话不存在
        '500':
          description: 服务器内部错误

  /workspace/ssh/download/{session_id}/{filename}:
    get:
      summary: 下载文件
      description: 从指定的 SSH 会话环境下载文件
      operationId: downloadFile
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
          description: 会话ID
        - name: filename
          in: path
          required: true
          schema:
            type: string
          description: 文件名
      responses:
        '200':
          description: 文件下载成功
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: 文件不存在
        '500':
          description: 服务器内部错误

  /workspace/ssh/execute/{session_id}:
    post:
      summary: 执行命令
      description: 在指定的 SSH 会话环境中执行命令
      operationId: executeCommand
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
          description: 会话ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                command:
                  type: string
                  description: 要执行的命令
                timeout:
                  type: integer
                  default: 30
                  description: 命令超时时间（秒）
      responses:
        '200':
          description: 命令执行成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      stdout:
                        type: string
                      stderr:
                        type: string
                      returncode:
                        type: integer
        '404':
          description: 会话不存在
        '500':
          description: 服务器内部错误

  /workspace/ssh/files/{session_id}:
    get:
      summary: 列出文件
      description: 列出指定 SSH 会话环境中的所有文件
      operationId: listFiles
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
          description: 会话ID
      responses:
        '200':
          description: 文件列表获取成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      files:
                        type: array
                        items:
                          type: object
                          properties:
                            filename:
                              type: string
                            size:
                              type: integer
        '404':
          description: 会话不存在
        '500':
          description: 服务器内部错误

  /workspace/ssh/cleanup-all:
    post:
      summary: 清理所有环境
      description: 清理所有 SSH 虚拟环境
      operationId: cleanupAllEnvironments
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                force:
                  type: boolean
                  default: false
                  description: 是否强制清理（即使会话正在运行）
      responses:
        '200':
          description: 清理操作完成
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      total:
                        type: integer
                      success:
                        type: integer
                      failed:
                        type: array
                        items:
                          type: string
                      skipped:
                        type: array
                        items:
                          type: string
        '500':
          description: 服务器内部错误

  /workspace/ssh/doc:
    get:
      summary: 获取API文档
      description: 获取OpenAPI格式的API文档
      operationId: getApiDoc
      responses:
        '200':
          description: API文档获取成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    description: OpenAPI文档内容
        '500':
          description: 服务器内部错误

components:
  schemas:
    Error:
      type: object
      properties:
        detail:
          type: string
      required:
        - detail

tags:
  - name: Session
    description: 会话管理相关接口
  - name: File
    description: 文件操作相关接口
  - name: Command
    description: 命令执行相关接口
  - name: Workspace
    description: 工作区管理相关接口 